const TCP_CLIENT_HOST_DEFAULT = '153.44.253.27'
const TCP_CLIENT_PORT_DEFAULT = 5631

export const TCP_CLIENT_HOST = process.env.SEASTREAM_TCP_CLIENT_HOST || TCP_CLIENT_HOST_DEFAULT
export const TCP_CLIENT_PORT = Number(process.env.SEASTREAM_TCP_CLIENT_PORT) || TCP_CLIENT_PORT_DEFAULT